image: gitpod/workspace-postgres

tasks:
  - name: run back-end
    before: npm install pg dotenv
    init: npm install
    command: npm start

  - name: run front-end
    init: cd client && npm install
    command: cd client && npm start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: open-preview